#!/bin/bash

# Define the variables needed by your virtual machine Char 
# in the general env of your terminal, so that you can run 
# the docker ps command without errors. You have to fix 
# all four environment variables with one command, and 
# you are not allowed to use your shell’s builtin to set 
# these variables by hand.

# You have to run the command below directly from the 
# commandline, not by calling the script!
# ---------------------

# eval $(docker-machine env Char)

# ---------------------
# Tip: run `echo "$(docker-machine env Char)"` to
# understand what's happening
