#!/bin/bash

# Launch a wordpress container as a background task, 
# just for fun. The container should be named lair, its 
# 80 port should be bound to the 8080 port of the virtual
# machine, and it should be able to use the spawning-pool 
# container as a database service. You can try to access 
# lair on your machine via a web browser, with the
# IP address of the virtual machine as a URL. Congratulations, 
# you just deployed a functional Wordpress website in 
# two commands!

docker run \
-d \
--name lair \
-p 8080:80 \
--link spawning-pool \
-e WORDPRESS_DB_HOST=spawning-pool \
-e WORDPRESS_DB_PASSWORD=Kerrigan \
-e WORDPRESS_DB_NAME=zerglings \
wordpress

# To check use some browser:
# -------------
# lynx "$(docker-machine ip Char):8080"

# Docs:
# -------------
# https://hub.docker.com/_/wordpress
