#!/bin/bash

# Launch a phpmyadmin container as a background task. 
# It should be named roach-warden, its 80 port should be 
# bound to the 8081 port of the virtual machine and it should
# be able to explore the database stored in the spawning-pool 
# container.

docker run \
-d \
--name roach-warden \
-p 8081:80 \
--link spawning-pool \
-e PMA_HOST=spawning-pool \
-e PMA_USER=root \
-e PMA_PASSWORD=Kerrigan \
phpmyadmin

# To check use some browser:
# -------------
# lynx "$(docker-machine ip Char):8081"

# Docs:
# -------------
# https://hub.docker.com/_/phpmyadmin
