#!/bin/bash

# Launch a container name Abathur. It will be a Python container, 
# 2-slim version, its /root folder will be bound to a HOME folder 
# on your host, and its 3000 port will be bound to the 3000 port 
# of your virtual machine. You will personalize this container 
# so that you can use the Flask micro-framework in its latest 
# version. You will make sure that an html page displaying 
# "Hello World" with <h1> tags can be served by Flask. You will 
# test that your container is properly set up by accessing, via 
# curl or a web browser, the IP address of your virtual machine 
# on the 3000 port. You will also list all the necessary commands 
# in your repository.

# It appears to be that Python is no longer supporting v.2 images
# So instead of official image i use alternative one

docker run \
--name Abathur \
-v ~:/root \
-p 3000:3000 \
-e FLASK_RUN_PORT=3000 \
-e FLASK_APP=hello.py \
-it \
frolvlad/alpine-python2


# -------------------
# Stage 01: Run inside the container:
# -------------------

# pip install flask
# mkdir /opt/flask
# cd /opt/flask || exit
# apk add vim
# vim hello.py

# -------------------
# hello.py
# -------------------

# from flask import Flask
# app = Flask(__name__)

# @app.route('/')
# def hello_world():
#    return '<h1>Hello World</h1>'

# -------------------
# Stage 02: Run inside the container:
# -------------------

# flask run --host=0.0.0.0

# -------------------
# Stage 03: Run on the host:
# -------------------

# curl "$(docker-machine ip Char):3000"
