#!/bin/bash

# Turn Aiur into a slave of the local swarm in which Char is 
# leader (the command to take control of Aiur is not requested).

# Step 1.
# Ssh to the Aiur VM via `docker-machine ssh Aiur`

# Step 2.
# Paste and run command from the ex20's output

# Step 3.
# Check swarm status via `docker node ls` from the host or
# swarm manager (Char)
