#!/bin/bash

# Launch a 42school/engineering-bay service in two replicas and 
# make sure that the service works properly (see the documentation 
# provided at hub.docker.com). This service will be named 
# engineering-bay and will be on the overmind network.

docker service create \
--replicas 2 \
-e OC_USERNAME=jim \
-e OC_PASSWD=raynor \
--name engineering-bay \
--network overmind \
42school/engineering-bay

# Docs: https://hub.docker.com/r/42school/engineering-bay/
